# Generated by Django 3.1 on 2020-09-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogunsoladebayoscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
